[phases.setup]
nixPkgs = ['php83', 'php83Extensions.mbstring', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.openssl', 'php83Extensions.tokenizer', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.zip', 'php83Extensions.dom', 'php83Extensions.fileinfo']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['php artisan config:cache', 'php artisan route:cache']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'